import { VT323 } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar";

const vtFont = VT323({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Shows up in all pages!
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={vtFont.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
